export const DEVICE_TYPES = {
  HR_SENSOR: "HR_SENSOR",
  LIGHT_SENSOR: "LIGHT_SENSOR",
  COLOR_SENSOR: "COLOR_SENSOR",
  TEMPERATURE_SENSOR: "TEMPERATURE_SENSOR",
  GAS_SENSOR: "GAS_SENSOR",
  HUMIDITY_SENSOR: "HUMIDITY_SENSOR",
  PRESSURE_SENSOR: "PRESSURE_SENSOR",
};
