export const DEVICE_TYPES = {
  HR_SENSOR: "HR_SENSOR",
  LIGHT_SENSOR: "LIGHT_SENSOR",
  COLOR_SENSOR: "COLOR_SENSOR",
  TEMPERATURE_SENSOR: "TEMPERATURE_SENSOR",
  GAS_SENSOR: "GAS_SENSOR",
  HUMIDITY_SENSOR: "HUMIDITY_SENSOR",
  PRESSURE_SENSOR: "PRESSURE_SENSOR",
};

export const DEVICE_TYPES_MAX_VALUES = {
  HR_SENSOR: 130,
  TEMPERATURE_SENSOR: 310,
  GAS_SENSOR: 1200,
  HUMIDITY_SENSOR: 70,
  PRESSURE_SENSOR: 101325,
};


export const PIE_CHART_COLORS = [
  "#E38627",
  "#C13C37",
  "#6A2135",
  "#04C1F7",
  "#CDD8E3",
  "#044C84",
  "#C24A37",
];